version: '3'
services:
  # service名
  app:
    # コンテナ名
    container_name: workbok-docker-compose
    # ビルドに使用するDockerfileがあるディレクトリ指定
    build: .
    tty: true
    # マウントディレクトリ指定
    volumes:
      - .:/go/src/work
    ports:
      - "8080:8080"
