#テストデプロイ5
# Goランタイム環境。
runtime: go113

#サービス名
service: Workbook

# インスタンス設定
instance_class: F1

#アクセス振り分け
handlers:
  - url: /web/js/
    static_dir: web/js/

  - url: /web/css/
    static_dir: web/css/

  - url: /web/img/
    static_dir: web/img/

  - url: /
    secure: always
    script: auto